---
  - name: Get facts for {{ url }}
    purefa_info:
      gather_subset: all
      fa_url: "{{ url }}"
      api_token: "{{ api }}"
    register: array_facts

  - set_fact:
      array_name: "{{ array_facts.purefa_info.default.array_name }}"

  - name: Set NTP for {{ url }}
    purefa_ntp:
      ntp_servers: "{{ ntp_servers }}"
      fa_url: "{{ url }}"
      api_token: "{{ api }}"
    when: array_facts.purefa_info.config.ntp != ntp_servers
