---
  - name: Get facts for {{ url }}
    purefa_info:
      gather_subset: all
      fa_url: "{{ url }}"
      api_token: "{{ api }}"
    register: array_facts
  
  - name: Facts for {{ url }}
    debug:
      msg: 
      - "array_name : {{ array_facts.purefa_info.default.array_name }}"
      - "array_model : {{ array_facts.purefa_info.default.array_model }}"
      - "purity_version : {{ array_facts.purefa_info.default.purity_version }}"
      - "hosts : {{ array_facts.purefa_info.default.hosts }}"
      - "phonehome : {{ array_facts.purefa_info.config.phonehome }}"
      - "proxy: {{ array_facts.purefa_info.config.proxy }}"
      - "syslog servers : {{ array_facts.purefa_info.config.syslog }}"
      - "dns : {{ array_facts.purefa_info.config.dns }}"
      - "ntp : {{ array_facts.purefa_info.config.ntp }}"
      - "ds uris: {{ array_facts.purefa_info.config.directory_service.uri }}"
      - "ds bind_user: {{ array_facts.purefa_info.config.directory_service.bind_user }}"
      - "smtp relayhost : {{ array_facts.purefa_info.config.relayhost }}"
      - "vip : {{ array_facts.purefa_info.network.vir0.address }}"
      - "ct0 : {{ array_facts.purefa_info.network['ct0.eth0'].address }}"
      - "ct1 : {{ array_facts.purefa_info.network['ct1.eth0'].address }}"

