---
  - name: Get facts for {{ url }}
    purefa_info:
      gather_subset: all
      fa_url: "{{ url }}"
      api_token: "{{ api }}"
    register: array_facts

  - set_fact:
      array_name: "{{ array_facts.purefa_info.default.array_name }}"

  - name: Configure DNS server settings for {{ url }}
    purefa_dns:
      domain: "{{ dns_domain }}"
      nameservers: "{{ dns_address }}"
      fa_url: "{{ url }}"
      api_token: "{{ api }}"
    when: (array_facts.purefa_info.config.dns.domain != dns_domain) or
          (array_facts.purefa_info.config.dns.nameservers != dns_address)
