---
  - name: Get facts for {{ url }}
    purefa_info:
      gather_subset: all
      fa_url: "{{ url }}"
      api_token: "{{ api }}"
    register: array_facts

  - set_fact:
      array_name: "{{ array_facts.purefa_info.default.array_name }}"

  - name: Create new user ai6disc with API token for {{ url }}
    purefa_user:
      name: ai6disc
      password: "{{ monitor_pass }}"
      role: readonly
      api: true
      fa_url: "{{ url }}"
      api_token: "{{ api }}"
    when: '"ai6disc" not in array_facts.purefa_info.admins'

  - name: API Token
    debug:
      msg: "API Token: {{ ansible_facts['user_api'] }}"
    when: '"ai6disc" not in array_facts.purefa_info.admins'
